# Generated by Django 2.0.9 on 2023-11-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REA_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_review',
            name='rating',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
