# Generated by Django 2.0.9 on 2023-12-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REA_app', '0002_app_review_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='requests',
        ),
    ]
