# Generated by Django 2.0.9 on 2023-12-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REA_app', '0003_auto_20231209_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
