# Generated by Django 2.0.9 on 2024-01-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REA_app', '0004_chat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='userid',
        ),
        migrations.AddField(
            model_name='diary',
            name='date',
            field=models.CharField(default='0000-00-00', max_length=200),
        ),
        migrations.AddField(
            model_name='diary',
            name='time',
            field=models.CharField(default='00:00', max_length=200),
        ),
    ]
