# Generated by Django 2.0.9 on 2024-01-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REA_app', '0005_auto_20240111_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
