# Generated by Django 2.0.9 on 2024-01-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REA_app', '0006_auto_20240131_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
