# Generated by Django 2.0.9 on 2024-02-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REA_app', '0007_auto_20240131_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor_review',
            name='rating',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
